development:
  adapter: postgresql
  encoding: utf8
  database: yard_sale_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: yard_sale_test
  pool: 5

production:  
  adapter: postgresql
  encoding: utf8
  database: yard_sale
  pool: 5