# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 631a6b964e5f78e2f83d6f61050b443aa176ca1cde514cf03ab19b6c7be9480430c4d8e9dde12b30fe77b9950ba953f671aa31de7439762233a121287edce835

test:
  secret_key_base: a4aca0e2590a63ef15d2b05138590452a0efedf98af5d1bdfa9912f756c608d340cdf49b4cc75f2a7232ae5007e455c0207c8980848844d44d4d27fbdbf9f085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
